# This is a basic workflow to help you get started with Actions

name: echo-hello-with-python

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]



# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  echo-hello:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
      - uses: actions/checkout@v3
    
#       - name: clone reop
#         run: git clone https://github.com/DONGYEONKANG/mlops-github-action.git
        
      - name: print ls
        run: ls
        
      - name: print pwd
        run: pwd
        
      - name: python file
        run: python ./hello.py
        
