name: echo-hello

on: push

jobs:
  echo-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Set Python Version to 3.9
        uses: actions/setup-python@v3.1.1
        with:
          python-version: "3.10"

      - name: python version check 
        run: python --version
      
      - name: Run ls
        run: ls -al # 숨김 파일 및 폴더를 포함해 자세히 본다.
        
      - name: Run pwd
        run: pwd # print working directory
